# Generated by Django 5.1.2 on 2024-11-05 07:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="is_verified",
            field=models.IntegerField(
                choices=[(0, "Unverified"), (1, "Verified")],
                default=0,
                verbose_name="verification status",
            ),
        ),
    ]
