# Generated by Django 5.1.2 on 2024-11-11 13:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_alter_user_image_otp"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="google_id",
            field=models.BigIntegerField(
                blank=True, null=True, unique=True, verbose_name="Google ID"
            ),
        ),
    ]
