# Generated by Django 5.1.2 on 2024-11-11 13:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_user_google_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="google_id",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                unique=True,
                verbose_name="Google ID",
            ),
        ),
    ]
