# Generated by Django 5.1.2 on 2024-11-07 08:34

import django.db.models.deletion
import django_extensions.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PnrDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                (
                    "status",
                    models.IntegerField(
                        choices=[(0, "Inactive"), (1, "Active")],
                        default=1,
                        verbose_name="status",
                    ),
                ),
                (
                    "activate_date",
                    models.DateTimeField(
                        blank=True,
                        help_text="keep empty for an immediate activation",
                        null=True,
                    ),
                ),
                (
                    "deactivate_date",
                    models.DateTimeField(
                        blank=True,
                        help_text="keep empty for indefinite activation",
                        null=True,
                    ),
                ),
                ("pnr", models.IntegerField(verbose_name="pnr number")),
                (
                    "train_number",
                    models.CharField(max_length=8, verbose_name="train number"),
                ),
                (
                    "train_name",
                    models.CharField(max_length=132, verbose_name="train name"),
                ),
                ("boarding_date", models.DateField(verbose_name="boarding date")),
                (
                    "boarding_point",
                    models.CharField(max_length=8, verbose_name="boarding point"),
                ),
                ("reserved_from", models.CharField(verbose_name="reserved from")),
                (
                    "reserved_to",
                    models.CharField(max_length=8, verbose_name="reserved to"),
                ),
                (
                    "reserved_class",
                    models.CharField(max_length=8, verbose_name="reserved class"),
                ),
                (
                    "fare",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="fare"
                    ),
                ),
                (
                    "remark",
                    models.CharField(
                        blank=True, max_length=64, null=True, verbose_name="remark"
                    ),
                ),
                (
                    "train_status",
                    models.CharField(
                        blank=True,
                        max_length=64,
                        null=True,
                        verbose_name="train status",
                    ),
                ),
                (
                    "charting_status",
                    models.CharField(max_length=64, verbose_name="charting status"),
                ),
                ("expiry", models.DateTimeField(verbose_name="pnr expiry")),
            ],
            options={
                "verbose_name": "PNR Details",
            },
        ),
        migrations.CreateModel(
            name="PassengerDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=64, verbose_name="name")),
                (
                    "booking_status",
                    models.CharField(max_length=64, verbose_name="booking status"),
                ),
                (
                    "current_status",
                    models.CharField(max_length=64, verbose_name="current status"),
                ),
                (
                    "coach_position",
                    models.CharField(
                        blank=True,
                        max_length=64,
                        null=True,
                        verbose_name="coach position",
                    ),
                ),
                (
                    "pnr_details",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pnr_details",
                        to="pnr.pnrdetail",
                    ),
                ),
            ],
            options={
                "verbose_name": "Passenger Details",
            },
        ),
    ]
