# Generated by Django 5.1.2 on 2024-11-07 08:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pnr", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pnrdetail",
            name="pnr",
            field=models.BigIntegerField(verbose_name="pnr number"),
        ),
    ]
