# Generated by Django 5.1.2 on 2024-11-07 08:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pnr", "0002_alter_pnrdetail_pnr"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pnrdetail",
            name="boarding_date",
            field=models.DateTimeField(verbose_name="boarding date"),
        ),
    ]
