# Generated by Django 5.1.2 on 2024-11-07 09:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pnr", "0003_alter_pnrdetail_boarding_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="passengerdetail",
            name="pnr_details",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="passengers_details",
                to="pnr.pnrdetail",
            ),
        ),
    ]
