# Generated by Django 5.1.2 on 2024-11-08 09:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("pnr", "0005_alter_pnrdetail_boarding_point"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="passengerdetail",
            options={"verbose_name": "Passenger Detail"},
        ),
        migrations.AlterModelOptions(
            name="pnrdetail",
            options={"verbose_name": "PNR Detail"},
        ),
    ]
