# Generated by Django 5.1.2 on 2024-11-11 07:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quickpnr", "0002_alter_emailtemplate_email_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emailtemplate",
            name="email_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("verify_email", "Verify Email"),
                    ("registered", "Registered Successfully"),
                    ("pnr_details", "PNR Details"),
                    ("password_reset_done", "Password Reset Done"),
                    ("password_reset", "Password Reset"),
                ],
                max_length=50,
                null=True,
            ),
        ),
    ]
